version: '3.3'
services:
  waves-devnet:
    build:
      context: ./
      dockerfile: Dockerfile
    command: waves.conf
    deploy:
      endpoint_mode: vip
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints: [node.hostname == vm01]
    image: testing.wemic.io:5000/cryptochain/waves-devnet
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
        max-file: "10"
    networks:
      - web-services
    ports:
      - 6863:6863
      - 6869:6869
    volumes:
      - ./conf:/conf
      - ./data:/data

networks:
  web-services:
    external: true
